.TH "demo::Control" 3 "Mon Jun 6 2022" "GHS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
demo::Control \- a structure that contains control information for \fBWireMessage\fP objects  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ghs\-demo\-comms\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSequenceCounter\fP \fBsequence\fP =0"
.br
.RI "The sequence counter used to avoid duplicates or detect lost messagesa\&. "
.in -1c
.SH "Detailed Description"
.PP 
a structure that contains control information for \fBWireMessage\fP objects 

For now only includes the sequence counter 

.SH "Author"
.PP 
Generated automatically by Doxygen for GHS from the source code\&.
