.TH "/home/hook/ws/cadre/dev/distributed-leader-election/include/ghs/edge.h" 3 "Mon Jun 6 2022" "GHS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/hook/ws/cadre/dev/distributed-leader-election/include/ghs/edge.h \- Edge structure definition and functions\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'ghs/agent\&.h'\fP
.br
\fC#include <limits>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBle::ghs::Edge\fP"
.br
.RI "A struct to hold all the communication edge information\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBle\fP"
.br
.ti -1c
.RI " \fBle::ghs\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef unsigned long \fBle::ghs::metric_t\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBle::ghs::status_t\fP { \fBle::ghs::UNKNOWN\fP = 0, \fBle::ghs::MST\fP = 1, \fBle::ghs::DELETED\fP =-1 }"
.br
.RI "A status enumeration, for the ghs edges\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "Edge \fBle::ghs::worst_edge\fP ()"
.br
.ti -1c
.RI "bool \fBle::ghs::is_valid\fP (const Edge e)"
.br
.ti -1c
.RI "bool \fBle::ghs::is_valid\fP (const metric_t m)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const metric_t \fBle::ghs::WORST_METRIC\fP =std::numeric_limits<metric_t>::max()"
.br
.ti -1c
.RI "const metric_t \fBle::ghs::METRIC_NOT_SET\fP =0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Edge structure definition and functions\&. 


.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2022 California Institute of Technology (“Caltech”)\&. U\&.S\&. Government sponsorship acknowledged\&.
.RE
.PP
All rights reserved\&.
.PP
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
.PP
.IP "\(bu" 2
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer\&.
.IP "\(bu" 2
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution\&.
.IP "\(bu" 2
Neither the name of Caltech nor its operating division, the Jet Propulsion Laboratory, nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission\&.
.PP
.PP
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 'AS
  IS' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED\&. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for GHS from the source code\&.
