.TH "src/demo/ghs-demo-msgutils.h" 3 "Wed Jun 15 2022" "GHS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/demo/ghs-demo-msgutils.h \- Provides some convenience functions for dealing with \fBdemo::WireMessage\fP buffers\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'ghs/msg\&.h'\fP
.br
\fC#include <cstring>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "template<std::size_t NUM> \fBMsg\fP \fBfrom_bytes\fP (unsigned char b[NUM])"
.br
.RI "quick and dirty static-sized message move "
.ti -1c
.RI "template<std::size_t NUM> void \fBto_bytes\fP (const \fBMsg\fP &m, unsigned char b[NUM])"
.br
.RI "quick and dirty static-sized message move "
.ti -1c
.RI "\fBMsg\fP \fBfrom_bytes\fP (unsigned char *b, size_t b_sz)"
.br
.RI "non-static versions (w/ or w/o compression, depending on compile flags) "
.ti -1c
.RI "void \fBto_bytes\fP (const \fBMsg\fP &m, unsigned char *b, size_t &b_sz)"
.br
.RI "non-static versions (w/ or w/o compression, depending on compile flags) "
.in -1c
.SH "Detailed Description"
.PP 
Provides some convenience functions for dealing with \fBdemo::WireMessage\fP buffers\&. 

Copyright (c) 2022 California Institute of Technology (“Caltech”)\&. U\&.S\&. Government sponsorship acknowledged\&.
.PP
All rights reserved\&.
.PP
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
.PP
.IP "\(bu" 2
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer\&.
.IP "\(bu" 2
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution\&.
.IP "\(bu" 2
Neither the name of Caltech nor its operating division, the Jet Propulsion Laboratory, nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission\&.
.PP
.PP
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 'AS
  IS' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED\&. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE\&. 
.SH "Function Documentation"
.PP 
.SS "\fBMsg\fP from_bytes (unsigned char * b, size_t b_sz)"

.PP
non-static versions (w/ or w/o compression, depending on compile flags) Note that it will verify that the passed-in size is large enough to use\&.
.PP
\fBParameters\fP
.RS 4
\fIb\fP an unsigned char pointer to construct a \fBle::ghs::Msg\fP from 
.br
\fIsz\fP a size_t that provides the size of the buffer 
.RE
.PP
\fBReturns\fP
.RS 4
\fBle::ghs::Msg\fP constructed from the buffer bytes 
.RE
.PP

.SS "template<std::size_t NUM> \fBMsg\fP from_bytes (unsigned char b[NUM])"

.PP
quick and dirty static-sized message move 
.PP
\fBParameters\fP
.RS 4
\fINUM\fP a std::size_t that determines the size of the buffer to construct a \fBle::ghs::Msg\fP from 
.br
\fIb\fP an unsigned char array of size NUM (or larger) 
.RE
.PP

.SS "void to_bytes (const \fBMsg\fP & m, unsigned char * b, size_t & b_sz)"

.PP
non-static versions (w/ or w/o compression, depending on compile flags) Note that it will verify that the passed-in size is large enough to use\&.
.PP
\fBParameters\fP
.RS 4
\fIm\fP an \fBle::ghs::Msg\fP to convert to types 
.br
\fIb\fP an unsigned char pointer to copy the msg bytes into 
.br
\fIsz\fP a size_t that provides the size of the destination buffer 
.RE
.PP

.SS "template<std::size_t NUM> void to_bytes (const \fBMsg\fP & m, unsigned char b[NUM])"

.PP
quick and dirty static-sized message move 
.PP
\fBParameters\fP
.RS 4
\fINUM\fP a std::size_t that determines the size of the buffer to construct a \fBle::ghs::Msg\fP from 
.br
\fIm\fP a \fBle::ghs::Msg\fP to convert to bytes and copy to the buffer \fCb\fP 
.br
\fIb\fP an unsigned char array of size NUM (or larger) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for GHS from the source code\&.
