.TH "src/demo/ghs-demo-edgemetrics.cpp" 3 "Mon Jun 6 2022" "GHS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/demo/ghs-demo-edgemetrics.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'ghs\-demo\-edgemetrics\&.h'\fP
.br
\fC#include <algorithm>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBCommsEdgeMetric\fP \fBsym_metric\fP (const uint16_t agent_to, const uint16_t agent_from, const \fBKbps\fP kbps)"
.br
.RI "\fBDark magic\fP to provide a symmetric, unique link-metric based on throughput and the two agent ids "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2022 California Institute of Technology (“Caltech”)\&. U\&.S\&. Government sponsorship acknowledged\&.
.RE
.PP
All rights reserved\&.
.PP
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
.PP
.IP "\(bu" 2
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer\&.
.IP "\(bu" 2
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution\&.
.IP "\(bu" 2
Neither the name of Caltech nor its operating division, the Jet Propulsion Laboratory, nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission\&.
.PP
.PP
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 'AS
  IS' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED\&. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE\&. 
.SH "Function Documentation"
.PP 
.SS "\fBCommsEdgeMetric\fP sym_metric (const uint16_t agent_id, const uint16_t agent_from, const \fBKbps\fP kbps)"

.PP
\fBDark magic\fP to provide a symmetric, unique link-metric based on throughput and the two agent ids Required for proper execution of \fBle::ghs::GhsState\fP\&. The 64bit return value is composed of 32 bits of throguhput left-shifted by 32 bits, OR-masked with the larger agent id left shifted 16 bits, finally OR-masked with the lower agent id\&.
.PP
The resulting 'hashy-metric' is:
.PP
.IP "\(bu" 2
Unique, in that even with identical throughputs, no two pairs of agents will have identical comms metrics
.IP "\(bu" 2
Symmetrical, in that both agents, if they agree on throughput can agree on the metric to use
.IP "\(bu" 2
Dominated by throughput, so no two agent ids are somehow more important than raw transmission power
.PP
.PP
\fBSee also\fP
.RS 4
\fBle::ghs::metric_t\fP 
.PP
\fBle::ghs::GhsState\fP 
.PP
\fBdemo::Comms::little_iperf()\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for GHS from the source code\&.
