.TH "le::ghs::NoopPayload" 3 "Mon Jun 6 2022" "GHS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
le::ghs::NoopPayload \- No further action necessary (i\&.e\&., we have completed the MST construction)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <msg\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMsg\fP \fBto_msg\fP (\fBagent_t\fP to, \fBagent_t\fP from)"
.br
.in -1c
.SH "Detailed Description"
.PP 
No further action necessary (i\&.e\&., we have completed the MST construction) 

.SH "Author"
.PP 
Generated automatically by Doxygen for GHS from the source code\&.
