.TH "le::ghs::msg::InPartPayload" 3 "Wed Jun 15 2022" "GHS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
le::ghs::msg::InPartPayload \- Asks 'Are you in my partition'\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <msg\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBagent_t\fP \fBleader\fP"
.br
.ti -1c
.RI "\fBlevel_t\fP \fBlevel\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Asks 'Are you in my partition'\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for GHS from the source code\&.
