.TH "le::ghs::SrchRetPayload" 3 "Mon Jun 6 2022" "GHS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
le::ghs::SrchRetPayload \- Returns an edge that represents the minimum weight outgoing edge\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <msg\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMsg\fP \fBto_msg\fP (\fBagent_t\fP to, \fBagent_t\fP from)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBagent_t\fP \fBto\fP"
.br
.ti -1c
.RI "\fBagent_t\fP \fBfrom\fP"
.br
.ti -1c
.RI "\fBmetric_t\fP \fBmetric\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Returns an edge that represents the minimum weight outgoing edge\&. 

Returns an edge that represents the minimum weight outgoing edge (across paritions) from the MST subtree rooted at the sender\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for GHS from the source code\&.
