.TH "le::ghs::msg::Data" 3 "Wed Jun 15 2022" "GHS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
le::ghs::msg::Data
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBNoopPayload\fP \fBnoop\fP"
.br
.ti -1c
.RI "\fBSrchPayload\fP \fBsrch\fP"
.br
.ti -1c
.RI "\fBSrchRetPayload\fP \fBsrch_ret\fP"
.br
.ti -1c
.RI "\fBInPartPayload\fP \fBin_part\fP"
.br
.ti -1c
.RI "\fBAckPartPayload\fP \fBack_part\fP"
.br
.ti -1c
.RI "\fBNackPartPayload\fP \fBnack_part\fP"
.br
.ti -1c
.RI "\fBJoinUsPayload\fP \fBjoin_us\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for GHS from the source code\&.
