.TH "le::ghs::AckPartPayload" 3 "Mon Jun 6 2022" "GHS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
le::ghs::AckPartPayload \- States 'I am in your partition'\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <msg\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMsg\fP \fBto_msg\fP (\fBagent_t\fP to, \fBagent_t\fP from)"
.br
.in -1c
.SH "Detailed Description"
.PP 
States 'I am in your partition'\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for GHS from the source code\&.
