.TH "le::ghs::msg::NoopPayload" 3 "Wed Jun 15 2022" "GHS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
le::ghs::msg::NoopPayload \- No further action necessary (i\&.e\&., we have completed the MST construction)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <msg\&.h>\fP
.SH "Detailed Description"
.PP 
No further action necessary (i\&.e\&., we have completed the MST construction) 

.SH "Author"
.PP 
Generated automatically by Doxygen for GHS from the source code\&.
