.TH "le::ghs::msg::AckPartPayload" 3 "Wed Jun 15 2022" "GHS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
le::ghs::msg::AckPartPayload \- States 'I am in your partition'\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <msg\&.h>\fP
.SH "Detailed Description"
.PP 
States 'I am in your partition'\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for GHS from the source code\&.
