.TH "le::ghs::msg::JoinUsPayload" 3 "Wed Jun 15 2022" "GHS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
le::ghs::msg::JoinUsPayload \- Msgs to merge /absorb two partitions across a given edge\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <msg\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBagent_t\fP \fBjoin_peer\fP"
.br
.ti -1c
.RI "\fBagent_t\fP \fBjoin_root\fP"
.br
.ti -1c
.RI "\fBagent_t\fP \fBproposed_leader\fP"
.br
.ti -1c
.RI "\fBlevel_t\fP \fBproposed_level\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Msgs to merge /absorb two partitions across a given edge\&. 



.SH "Author"
.PP 
Generated automatically by Doxygen for GHS from the source code\&.
