.TH "le::ghs::msg::SrchPayload" 3 "Wed Jun 15 2022" "GHS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
le::ghs::msg::SrchPayload \- Requests a search begin in the MST subtree rooted at the receiver, for the minimum weight outgoing edge (one that spans two partitions)\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <msg\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBagent_t\fP \fByour_leader\fP"
.br
.ti -1c
.RI "\fBlevel_t\fP \fByour_level\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Requests a search begin in the MST subtree rooted at the receiver, for the minimum weight outgoing edge (one that spans two partitions)\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for GHS from the source code\&.
