.TH "le::ghs::Msg::Data" 3 "Mon Jun 6 2022" "GHS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
le::ghs::Msg::Data \- A union of all possible payloads\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <msg\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBNoopPayload\fP \fBnoop\fP"
.br
.ti -1c
.RI "\fBSrchPayload\fP \fBsrch\fP"
.br
.ti -1c
.RI "\fBSrchRetPayload\fP \fBsrch_ret\fP"
.br
.ti -1c
.RI "\fBInPartPayload\fP \fBin_part\fP"
.br
.ti -1c
.RI "\fBAckPartPayload\fP \fBack_part\fP"
.br
.ti -1c
.RI "\fBNackPartPayload\fP \fBnack_part\fP"
.br
.ti -1c
.RI "\fBJoinUsPayload\fP \fBjoin_us\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A union of all possible payloads\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for GHS from the source code\&.
