.TH "le::LocalGraph< SZ >::LocalEdge" 3 "Wed Jun 15 2022" "GHS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
le::LocalGraph< SZ >::LocalEdge
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBto\fP"
.br
.ti -1c
.RI "unsigned int \fBstatus\fP"
.br
.ti -1c
.RI "unsigned int \fBweight\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for GHS from the source code\&.
