.TH "md_CONTRIBUTING" 3 "Wed Jun 15 2022" "GHS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_CONTRIBUTING \- CONTRIBUTING 
We are not set up to support contributors very well, but would appreciate
.PP
.IP "\(bu" 2
testing on new systems
.IP "\(bu" 2
help with issues\&. Just please check in on the issue to make sure nobody is working on it yet!
.PP
.PP
Just please:
.PP
.IP "\(bu" 2
Work on a branch! If a branch doesn't exist (which is a good sign nobody is working on it), branch from main, and create a branch with the issue number and issue name\&. Github does this for you if you click \fCcreate a branc\fP on the bottom right
.IP "\(bu" 2
Issue pull requests to merge back to main, and fully document what you did
.IP "\(bu" 2
TEST your code, using the right \fC*-doctest\fP executable, or create one if you need to\&. 
.PP

