.TH "include/ghs/msg.h" 3 "Mon Jun 6 2022" "GHS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/ghs/msg.h \- provides the defs for the struct le::ghs::msg  

.SH SYNOPSIS
.br
.PP
\fC#include 'ghs/agent\&.h'\fP
.br
\fC#include 'ghs/level\&.h'\fP
.br
\fC#include 'ghs/edge\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBle::ghs::NoopPayload\fP"
.br
.RI "No further action necessary (i\&.e\&., we have completed the MST construction) "
.ti -1c
.RI "struct \fBle::ghs::SrchPayload\fP"
.br
.RI "Requests a search begin in the MST subtree rooted at the receiver, for the minimum weight outgoing edge (one that spans two partitions)\&. "
.ti -1c
.RI "struct \fBle::ghs::SrchRetPayload\fP"
.br
.RI "Returns an edge that represents the minimum weight outgoing edge\&. "
.ti -1c
.RI "struct \fBle::ghs::InPartPayload\fP"
.br
.RI "Asks 'Are you in my partition'\&. "
.ti -1c
.RI "struct \fBle::ghs::AckPartPayload\fP"
.br
.RI "States 'I am in your partition'\&. "
.ti -1c
.RI "struct \fBle::ghs::NackPartPayload\fP"
.br
.RI "States 'I am not in your partition'\&. "
.ti -1c
.RI "struct \fBle::ghs::JoinUsPayload\fP"
.br
.RI "Msgs to merge /absorb two partitions across a given edge\&. "
.ti -1c
.RI "struct \fBle::ghs::Msg\fP"
.br
.RI "An aggregate type containing all the data to exchange with to/from information\&. "
.ti -1c
.RI "union \fBle::ghs::Msg::Data\fP"
.br
.RI "A union of all possible payloads\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBle\fP"
.br
.ti -1c
.RI " \fBle::ghs\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const long long int \fBle::ghs::MAX_MSG_SZ\fP = sizeof(Msg)"
.br
.in -1c
.SH "Detailed Description"
.PP 
provides the defs for the struct le::ghs::msg 


.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2022 California Institute of Technology (“Caltech”)\&. U\&.S\&. Government sponsorship acknowledged\&.
.RE
.PP
All rights reserved\&.
.PP
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
.PP
.IP "\(bu" 2
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer\&.
.IP "\(bu" 2
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution\&.
.IP "\(bu" 2
Neither the name of Caltech nor its operating division, the Jet Propulsion Laboratory, nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission\&.
.PP
.PP
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 'AS
  IS' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED\&. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for GHS from the source code\&.
