.TH "seque" 3 "Wed Jun 15 2022" "GHS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
seque
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBStaticQueue\fP"
.br
.RI "a static-sized single-ended queue for use in GhsState "
.in -1c
.SH "Detailed Description"
.PP 
This namespace presents a Single Ended QUEue implementation that is part of the I/O with \fBle::ghs::GhsState\fP objects 
.SH "Author"
.PP 
Generated automatically by Doxygen for GHS from the source code\&.
