CPPFLAGS=--std=c++14 -ggdb -Wall -fshort-enums
all: 
	g++ $(CPPFLAGS) ghs.cpp msg.cpp ghs-score.cpp -o ghs-score
	g++ $(CPPFLAGS) middle-leader.cpp -o middle-leader
	g++ $(CPPFLAGS) stleader.cpp -o stleader
	g++ $(CPPFLAGS) random-graph.cpp -o random-graph
	g++ $(CPPFLAGS) to-dot.cpp -o to-dot
