name: Docs

on:
  push:
    branches: [ "20-autodocs-and-gh-pages" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  DOCS: 20-autodocs-deploy

jobs:
  build-docs:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get Dependencies
      # Use script to download dependencies for build/test
      working-directory: ${{github.workspace}}
      run: sudo ./get_deps.sh

    - name: Get main
      working-directory: ${{github.workspace}}
      run: git fetch  && git checkout "$DOCS"

    - name: Clean docs
      working-directory: ${{github.workspace}}
      run: git rm -rf docs/

    - name: Get last changes
      working-directory: ${{github.workspace}}
      run: git merge main

    - name: CMake Doxygen
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: |
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_DOCTEST=Off -DBUILD_DOCS=On -DBUILD_DEMO=Off
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target doxygen

    - name: Config user
      run: |
        git config --local user.email "23857237+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"

    - name: Force docs
      working-directory: ${{github.workspace}}
      run: git add docs/ -f && git commit -am "docs built by github-action from main"

    - name: Push DOCS
      working-directory: ${{github.workspace}}
      run: git push origin "$DOCS" -f

